service:
  url: ${SERVICE_ENDPOINT:http://localhost:9090}
  path: ${SERVICE_PATH:/some-service}

zuul:
  routes:
    some-service:
      path: ${service.path}/**
      strip-prefix: true
      url: ${service.url}

gateway:
  service-principal: ${SERVICE_PRINCIPAL:HTTP/localhost}
  keytab-location: ${KEYTAB_LOCATION:/tmp/minikdc/example.keytab}
