zuul:
  routes:
    some-service:
      path: /some-service/**
      stip-prefix: true
      url: http://localhost:9090

app:
  service-principal: HTTP/localhost
  keytab-location: /tmp/minikdc/example.keytab